In [1]:
#모듈 호출
import tensorflow as tf

#버전 출력
print(tf.__version__)


1.15.0


In [22]:
#상수 정의, 스칼라 값
a = tf.constant(1234) 
b = tf.constant(5000)

#계산 정의
add_op = a+b

#세션 시작 
sess = tf.Session()
#계산식 평가
res = sess.run(add_op)
print(res)

6234


In [47]:
#변수 v 선언하기
# variable은 하나의 객체가 된다 즉 클래스의 인스턴스가 생성되는 것이고  해당 인스턴스를 그래프에 추가시켜주어야 한다.
# 생성 후 global_variables_initializer()함수를 실행 해주어야 함,호출하기 전에 그래프의 상태는 각 노드에 값이 아직 없는 상태를 의미한다.따라서 해당 함수를 사용해주어야 Variable 의 값이 할당 되는 것이고 텐서의 그래프로써의 효력이 발생하는 것이다.
v = tf.Variable(10) #클래스의 생성자 함수, tf.zeros()로 설정가능, 

# 변수 v에 add_op의 결과 대입하기
let_op = tf.assign(v, add_op)

#세션 시작 
sess = tf.Session() 

# 변수 초기화히기 ,메모리에서 계산작업을 하기 위한 초기화(생성)
sess.run(tf.global_variables_initializer())

#계산식 실행
print(sess.run(let_op))
print(sess.run(v))

6234
6234


In [52]:
#placeholder 정의(정수 자료형 3개를 가진 배열)
#템플릿처럼 값을 넣을 공간을 만들어두는 기능
#데이터 플로우 그래프를 구축할 때는 값을 넣지 않고 값을 담을 수 있는 그릇만 만들어두고, 이후에 세션을 실행할 때 그릇에 값을 넣고 실행할 수 있다.

#a = tf.placeholder(tf.int32, [3])  # 비어있는 배열
a = tf.placeholder(tf.int32, [None])  # None 지정 시 , 가변으로 된다.
b = tf.constant(2)
x2_op = a* b

#세션 시작 
sess = tf.Session() 
# placeholder에 값 넣고 실행하기
r1 = sess.run(x2_op, feed_dict = {a:[1, 2, 3]})
print(r1)
r2 = sess.run(x2_op, feed_dict = {a:[10, 20, 10]})
print(r2)
r3 = sess.run(x2_op, feed_dict = {a:[10, 20, 10, 80]})
print(r3)

#다양한 함수들
"""
tensoflow.sqrt(x): x의 제곱근을 계산
tensoflow.reduce_mean(x): x의 평균을 계산
tensoflow.square(x): x의 제곱을 계산
random_uniform([1], 0, 10,…) : 0에서 10 사이에서 임의의 수 1개 생성 반환
Variable() : 변수의 값을 지정 
"""


[2 4 6]
[20 40 20]
[ 20  40  20 160]


'\ntensoflow.sqrt(x): x의 제곱근을 계산\ntensoflow.reduce_mean(x): x의 평균을 계산\ntensoflow.square(x): x의 제곱을 계산\nrandom_uniform([1], 0, 10,…) : 0에서 10 사이에서 임의의 수 1개 생성 반환\nVariable() : 변수의 값을 지정 \n'

In [53]:
# 데이터 플로우 그래프 구축하기  
# 아나콘다 프롬프트에서 작업중인 주피터노트북 경로로 가서 'tensorboard --logdir=./logs' 입력 웹에서 localhost:6006 접속 후  그래프로 확인 가능,
a = tf.constant(20, name="a")
b = tf.constant(30, name="b")
mul_op = a * b
# 세션 생성하기  
sess = tf.Session()
# TensorBoard 사용하기  
tw = tf.summary.FileWriter("log_dir", graph=sess.graph)
# 세션 실행하기 
print(sess.run(mul_op))

600


#### 선형 회귀 기울기 와 절편 구하기

In [60]:
#최소 제곱법
import numpy as np

# x 값과 y 값
x = [2, 4, 6, 8]
y = [81, 93, 91, 97]

# x와 y의 평균값
mx = np.mean(x)
my = np.mean(y)

# 기울기 공식의 분모
divisor = sum([(mx-i)**2 for i in x])


# 기울기 공식의 분자
def top(x, mx, y, my):
    d = 0
    for i in range(len(x)):
        d += (x[i] - mx)*(y[i] - my)
    return d


# 기울기와 y 절편 구하기
a = top(x, mx,y, my)/divisor  #기울기
b = my - (mx * a) # y 절편

# 출력으로 확인
print("기울기 : ", a)
print("Y 절편 : ", b)

기울기 :  2.3
Y 절편 :  79.0


In [73]:
# 평균 제곱 오차 구하기
import numpy as np

# 기울기 a와 y 절편 b
ab = [2.3,76]

# x, y의 데이터 값
data = [[2,81],[4,93],[6,91],[8,97]]
x = [i[0] for i in data]
y = [i[1] for i in data]


# y = ax + b에 a와 b 값을 대입하여 결과를 출력하는 함수
#print('y = {0}x + {1}',format(a, b))

# 임의의 기울기와 절편의 모델로 부터 예측값 반환 함수
def predict(x):
    return ab[0]*x + ab[1]

# 예측 값이 들어갈 빈 리스트
predict_result = []

# RMSE(평균 제곱근 오차 반환 함수)
def rmse(p,a):
    return np.sqrt(((p-a)**2).mean())


for i in range(len(x)):
    predict_result.append(predict(x[i]))
    print("공부한 시간= %.f, 실제점수=%.f, 예측점수=%.f" %(x[i], y[i], predict_result[i]) )

# RMSE 함수를 각 y 값에 대입하여 최종 값을 구하는 함수
def rmse_val(predict_result, y ):
    return rmse(np.array(predict_result), np.array(y))



# 최종 RMSE 출력
print("rmse 최종값: ", str(rmse_val(predict_result,y))) 


공부한 시간= 2, 실제점수=81, 예측점수=81
공부한 시간= 4, 실제점수=93, 예측점수=85
공부한 시간= 6, 실제점수=91, 예측점수=90
공부한 시간= 8, 실제점수=97, 예측점수=94
rmse 최종값:  4.159326868617082


In [71]:
import numpy as np

#  임의의 기울기와 절편
ab = [3, 76]

data = [[2,81],[4,93],[6,91],[8,97]]

# x 값과 y 값
x= [ i[0] for i in data]
y= [ i[1] for i in data]


#  임의의 기울기와 절편의 모델로부터 예측값 반환 함수
def predict(x):
    return ab[0]*x+ab[1]

# 평균 제곱근 오차 반환 함수
def rmse(p, a):
    return    np.sqrt(((p-a)**2).mean())

predict_result = []

for i in range(len(x)):
    predict_result.append(predict(x[i]))
    print("공부한 시간 =%.f, 실제 점수 =%.f,  예측점수=%.f" % (x[i], y[i], predict_result[i]))

# 평균 제곱근 오차 반환 함수를 이용해서 최종값 구하기
def  rmse_val(predict_result, y) :
    return rmse(np.array(predict_result), np.array(y))

print("rmse  최종값 :"+ str(rmse_val(predict_result, y)))



공부한 시간 =2, 실제 점수 =81,  예측점수=82
공부한 시간 =4, 실제 점수 =93,  예측점수=88
공부한 시간 =6, 실제 점수 =91,  예측점수=94
공부한 시간 =8, 실제 점수 =97,  예측점수=100
rmse  최종값 :3.3166247903554
