## 3. Decision Tree
 - P.116

### 암세포 데이터로 분석

In [4]:
import pandas as pd
import numpy as np


In [18]:
uci_path='http://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data'
df =pd.read_csv(uci_path, header=None)
df.columns=['id', 'clump', 'cell_size', 'cell_shape', 'adhesion', 'epithlial', 'bare_nuclei', 'chromation', 'normal_nucleoli', 'mitoses', 'class']

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
id                 699 non-null int64
clump              699 non-null int64
cell_size          699 non-null int64
cell_shape         699 non-null int64
adhesion           699 non-null int64
epithlial          699 non-null int64
bare_nuclei        699 non-null object
chromation         699 non-null int64
normal_nucleoli    699 non-null int64
mitoses            699 non-null int64
class              699 non-null int64
dtypes: int64(10), object(1)
memory usage: 60.2+ KB


In [47]:
df['class'].unique()

array([2, 4], dtype=int64)

In [20]:
df.describe()

id       clump   cell_size  cell_shape    adhesion  \
count  6.990000e+02  699.000000  699.000000  699.000000  699.000000   
mean   1.071704e+06    4.417740    3.134478    3.207439    2.806867   
std    6.170957e+05    2.815741    3.051459    2.971913    2.855379   
min    6.163400e+04    1.000000    1.000000    1.000000    1.000000   
25%    8.706885e+05    2.000000    1.000000    1.000000    1.000000   
50%    1.171710e+06    4.000000    1.000000    1.000000    1.000000   
75%    1.238298e+06    6.000000    5.000000    5.000000    4.000000   
max    1.345435e+07   10.000000   10.000000   10.000000   10.000000   

        epithlial  chromation  normal_nucleoli     mitoses       class  
count  699.000000  699.000000       699.000000  699.000000  699.000000  
mean     3.216023    3.437768         2.866953    1.589413    2.689557  
std      2.214300    2.438364         3.053634    1.715078    0.951273  
min      1.000000    1.000000         1.000000    1.000000    2.000000  
25%      2.000000    2.000000         1.000000    1.000000    2.000000  
50%      2.000000    3.000000         1.000000    1.000000    2.000000  
75%      4.000000    5.000000         4.000000    1.000000    4.000000  
max     10.000000   10.000000        10.000000   10.000000    4.000000

In [23]:
print(df['bare_nuclei'].unique())
print(df['bare_nuclei'].value_counts)

['1' '10' '2' '4' '3' '9' '7' '?' '5' '8' '6']
<bound method IndexOpsMixin.value_counts of 0       1
1      10
2       2
3       4
4       1
       ..
694     2
695     1
696     3
697     4
698     5
Name: bare_nuclei, Length: 699, dtype: object>


In [25]:
# Null 값을 만들고 삭제
df['bare_nuclei'].replace('?', np.nan, inplace=True)
df.dropna(subset=['bare_nuclei'], axis=0, inplace=True) #행 기준 삭제
df['bare_nuclei'] = df['bare_nuclei'].astype('int')

In [26]:
df.info()
print(df['bare_nuclei'].unique())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 683 entries, 0 to 698
Data columns (total 11 columns):
id                 683 non-null int64
clump              683 non-null int64
cell_size          683 non-null int64
cell_shape         683 non-null int64
adhesion           683 non-null int64
epithlial          683 non-null int64
bare_nuclei        683 non-null int32
chromation         683 non-null int64
normal_nucleoli    683 non-null int64
mitoses            683 non-null int64
class              683 non-null int64
dtypes: int32(1), int64(10)
memory usage: 61.4 KB
[ 1 10  2  4  3  9  7  5  8  6]


In [29]:
#변수 설정

#설명변수(독립변수)
X = df[['id', 'clump', 'cell_size', 'cell_shape', 'adhesion', 'epithlial', 'bare_nuclei', 'chromation', 'normal_nucleoli', 'mitoses']]
print(X)
#종속변수(예측변수, 반응변수)
Y = df['class']

          id  clump  cell_size  cell_shape  adhesion  epithlial  bare_nuclei  \
0    1000025      5          1           1         1          2            1   
1    1002945      5          4           4         5          7           10   
2    1015425      3          1           1         1          2            2   
3    1016277      6          8           8         1          3            4   
4    1017023      4          1           1         3          2            1   
..       ...    ...        ...         ...       ...        ...          ...   
694   776715      3          1           1         1          3            2   
695   841769      2          1           1         1          2            1   
696   888820      5         10          10         3          7            3   
697   897471      4          8           6         4          3            4   
698   897471      4          8           8         5          4            5   

     chromation  normal_nucleoli  mitos

In [30]:
# 설명변수 데이터 정규화
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
print(X)



[[-0.12366418  0.19790469 -0.70221201 ... -0.18182716 -0.61292736
  -0.34839971]
 [-0.11895594  0.19790469  0.27725185 ... -0.18182716 -0.28510482
  -0.34839971]
 [-0.09883306 -0.51164337 -0.70221201 ... -0.18182716 -0.61292736
  -0.34839971]
 ...
 [-0.30297227  0.19790469  2.23617957 ...  1.86073779  2.33747554
   0.22916583]
 [-0.2890233  -0.15686934  1.58320366 ...  2.67776377  1.02618536
  -0.34839971]
 [-0.2890233  -0.15686934  1.58320366 ...  2.67776377  0.37054027
  -0.34839971]]


In [32]:
#train/test set 7:3으로 분리
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y , test_size= 0.3 , random_state=10)
print(X_train.shape)
print(X_test.shape)

(478, 10)
(205, 10)


In [56]:
# Decision Tree 분류 생성
from sklearn import tree

tree_model = tree.DecisionTreeClassifier(criterion='gini', max_depth=100)
tree_model.fit(X_train, Y_train)

y_predict = tree_model.predict(X_test)

In [35]:
print(y_predict[:10])
print(Y_test.values[:10])

[4 4 4 4 4 4 2 2 4 4]
[4 4 4 4 4 4 2 2 4 4]


In [51]:
#criterion='entropy'
# max_depth = 5
from sklearn import metrics
tree_matrix = metrics.confusion_matrix(Y_test, y_predict)
print(tree_matrix)

tree_report = metrics.classification_report(Y_test, y_predict)
print(tree_report)

[[127   4]
 [  2  72]]
              precision    recall  f1-score   support

           2       0.98      0.97      0.98       131
           4       0.95      0.97      0.96        74

    accuracy                           0.97       205
   macro avg       0.97      0.97      0.97       205
weighted avg       0.97      0.97      0.97       205



In [49]:
#criterion='entropy'
# max_depth = 10
from sklearn import metrics
tree_matrix = metrics.confusion_matrix(Y_test, y_predict)
print(tree_matrix)

tree_report = metrics.classification_report(Y_test, y_predict)
print(tree_report)

[[127   4]
 [  2  72]]
              precision    recall  f1-score   support

           2       0.98      0.97      0.98       131
           4       0.95      0.97      0.96        74

    accuracy                           0.97       205
   macro avg       0.97      0.97      0.97       205
weighted avg       0.97      0.97      0.97       205



In [44]:
#criterion='entropy'
# max_depth = 100
from sklearn import metrics
tree_matrix = metrics.confusion_matrix(Y_test, y_predict)
print(tree_matrix)

tree_report = metrics.classification_report(Y_test, y_predict)
print(tree_report)

[[127   4]
 [  3  71]]
              precision    recall  f1-score   support

           2       0.98      0.97      0.97       131
           4       0.95      0.96      0.95        74

    accuracy                           0.97       205
   macro avg       0.96      0.96      0.96       205
weighted avg       0.97      0.97      0.97       205



In [53]:
#criterion='gini'
# max_depth = 5
from sklearn import metrics
tree_matrix = metrics.confusion_matrix(Y_test, y_predict)
print(tree_matrix)

tree_report = metrics.classification_report(Y_test, y_predict)
print(tree_report)


[[127   4]
 [  5  69]]
              precision    recall  f1-score   support

           2       0.96      0.97      0.97       131
           4       0.95      0.93      0.94        74

    accuracy                           0.96       205
   macro avg       0.95      0.95      0.95       205
weighted avg       0.96      0.96      0.96       205



In [55]:
#criterion='gini'
# max_depth = 10
from sklearn import metrics
tree_matrix = metrics.confusion_matrix(Y_test, y_predict)
print(tree_matrix)

tree_report = metrics.classification_report(Y_test, y_predict)
print(tree_report)


[[127   4]
 [  7  67]]
              precision    recall  f1-score   support

           2       0.95      0.97      0.96       131
           4       0.94      0.91      0.92        74

    accuracy                           0.95       205
   macro avg       0.95      0.94      0.94       205
weighted avg       0.95      0.95      0.95       205



In [57]:
#criterion='gini'
# max_depth = 100
from sklearn import metrics
tree_matrix = metrics.confusion_matrix(Y_test, y_predict)
print(tree_matrix)

tree_report = metrics.classification_report(Y_test, y_predict)
print(tree_report)


[[127   4]
 [  5  69]]
              precision    recall  f1-score   support

           2       0.96      0.97      0.97       131
           4       0.95      0.93      0.94        74

    accuracy                           0.96       205
   macro avg       0.95      0.95      0.95       205
weighted avg       0.96      0.96      0.96       205



```bash
[[127   4]
 [  5  69]]
              precision    recall  f1-score   support

           2       0.96      0.97      0.97       131
           4       0.95      0.93      0.94        74

    accuracy                           0.96       205
   macro avg       0.95      0.95      0.95       205
weighted avg       0.96      0.96      0.96       205
```

In [58]:
pip install pydotplus

  Created wheel for pydotplus: filename=pydotplus-2.0.2-cp37-none-any.whl size=24573 sha256=da441403d8882804208f89cacfcbd3c99cec4de8191c5065ce4e8d90c20ab466
  Stored in directory: C:\Users\student\AppData\Local\pip\Cache\wheels\35\7b\ab\66fb7b2ac1f6df87475b09dc48e707b6e0de80a6d8444e3628
Successfully built pydotplus
Note: you may need to restart the kernel to use updated packages.


In [ ]:
from pydotplus import graph_from_dot_data
from sklearn.tree import export_graphviz
dot_data = export_graphviz(tree, filled = True)