In [2]:
import numpy as np
import numpy.linalg as lin 

#numpy는 다차원 배열을 처리하는데 빠르다.

In [15]:
a = np.array([[1,1],[2,1]])
print(a)
print(a.shape)

#역행렬 구하기
a_ = lin.inv(a)
print(a_)

[[1 1]
 [2 1]]
(2, 2)
[[-1.  1.]
 [ 2. -1.]]


In [23]:
y = np.array([2,4]) 
print(y)
print(y.shape) #1차원 벡터
print()

y_1 = np.array([[2,4]])
print(y_1)
print(y_1.shape) #컬럼 벡터가 아님
print()

y_2 = np.array([[2], [4]])
print(y_2)
print(y_2.shape) #컬럼 벡터가 아님
print()

[2 4]
(2,)

[[2 4]]
(1, 2)

[[2]
 [4]]
(2, 1)



In [28]:
#reshape 를 통해 배열 사이즈 재조정
y = np.array([2,4]).reshape(2,1)
print(y)
print(y.shape)
print()

[[2]
 [4]]
(2, 1)

[[2.]
 [0.]]
(2, 1)


In [29]:
#넘파이는 일반연산(산술)과 행렬연산을 구별한다.
#일반연산
w = a_ * y
print(w)
print(w.shape)
print()

#행렬연산
w = np.matmul(a_,y)
print(w)
print(w.shape)

[[-2.  2.]
 [ 8. -4.]]
(2, 2)

[[2.]
 [0.]]
(2, 1)


In [34]:
a = np.array([[1,1], [2,1], [3,1]   ]) #정방행렬이 아니라 에러가 발생, P를 넣어줘야 함
#lin.inv(a)
a_ = lin.pinv(a)
print(a_)
print()

y = np.array([2,4,6.4]).reshape(3,1)
w = np.matmul(a_, y)
print(w)

[[-5.00000000e-01 -3.19189120e-16  5.00000000e-01]
 [ 1.33333333e+00  3.33333333e-01 -6.66666667e-01]]

[[ 2.2       ]
 [-0.26666667]]


In [36]:
print(w[0][0]) #이차원 행렬이므로 [0][0] 으로 사용

2.2000000000000006


In [40]:
#x가 1일 떄 y는?
#y= wx + b
#y = w[0,0] * 1 + w[1,0]

y = w[0,0] * np.arange(-10,10) + w[1,0] # w[0,0]은 w값, w[1,0]은 b 값
print(y)#1.9333333333333322


[-22.26666667 -20.06666667 -17.86666667 -15.66666667 -13.46666667
 -11.26666667  -9.06666667  -6.86666667  -4.66666667  -2.46666667
  -0.26666667   1.93333333   4.13333333   6.33333333   8.53333333
  10.73333333  12.93333333  15.13333333  17.33333333  19.53333333]
